# Generated by Django 3.0.7 on 2020-07-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videoSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_video', models.CharField(max_length=200, verbose_name='Название книги')),
                ('date_video', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата публикации')),
                ('image_video', models.ImageField(blank=True, upload_to='image/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'Видео',
            },
        ),
    ]
