# Generated by Django 3.0.7 on 2020-07-15 07:49

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('appVideoProgramming', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videosite',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='videosite',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=''),
        ),
        migrations.AlterField(
            model_name='videosite',
            name='image_video',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='videosite',
            name='title_video',
            field=models.CharField(max_length=200, verbose_name='Название видео'),
        ),
    ]
