# Generated by Django 3.0.7 on 2020-07-15 11:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appVideoProgramming', '0002_auto_20200715_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosite',
            name='redactor_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
